### ISSUE TITLE
wd-icon-sort is missing in the icon CDN

### ISSUE THREAD

**Issue by aaronanderson** [Workday/canvas-kit#409]
## 🐛 Bug Report

Using the canvas-kit-css-icon module with this HTML 
```
<i class="wdc-icon" data-icon="sort" data-category="system"></i>
```
when it renders I receive this browser error:

`svg-injector.js:179 GET https://design.workdaycdn.com/beta/assets/web-icons/system@0.11.16/svg/wd-icon-sort.svg 403 (Forbidden)`

This icon is listed on the [design site](https://design.workday.com/tokens/assets/icons/system-icons), the filter icon works, and I can see `@workday/canvas-system-icons-web/dist/svg/wd-icon-sort.svg` in my local node_modules directory so I am not sure why the sort icons were not published to the CDN.

**Comment by lychyi** [comment]
Thanks @aaronanderson 

We will take a look, this is probably just because of a legacy issue we haven't addressed in a while

**Comment by jpante** [comment]
Awaiting CDN latest changes from @josephnle

**Comment by NicholasBoll** [comment]
I've verified this is still an issue. I think we'll need to update the version of icons we use. Our version is out of date.

**Comment by jaclynjessup** [comment]
This icon is present within the canvas site today. And is available within the icon package
